dataset:
  dir: '/mnt/datasets/isles24_combined'
  json_list: '/mnt/datasets/isles24_combined/isles24_multimodal_5fold_NIHSSstratified.json'
  num_workers: 48
  train_batch_size: 4
  test_batch_size: 4
training:
  output_root: '/mnt/outputs/'
  model_save_dir: 'models/'
  multi_gpu: false
device: cuda
