dataset:
  data_root: '/mnt/c/Users/minanessiem/Development/isles24_combined'
  split_file: '/mnt/c/Users/minanessiem/Development/isles24_combined/isles24_multimodal_5fold_NIHSSstratified.json'
  nnunet_root: null
training:
  output_root: './outputs/'
  model_save_dir: 'models/'
  multi_gpu: false
device: cuda
