dataset:
  data_root: '/mnt/datasets/isles26_combined/atlas21_training_raw/Training_Raw'
  split_file: '/mnt/datasets/isles26_combined/atlas21_training_raw/isles26_nested_15_5_best.json'
  nnunet_root: '/mnt/datasets/nnunet_raw'
training:
  output_root: '/mnt/outputs/medsegdiff_isles26_outputs/'
  model_save_dir: 'models/'
  multi_gpu: false
device: cuda
