dataset:
  data_root: '/mnt/datasets/isles24_combined'
  split_file: '/mnt/datasets/isles24_combined/isles24_multimodal_5fold_NIHSSstratified.json'
  nnunet_root: null
training:
  output_root: '/mnt/outputs/medsegdiff_outputs/'
  model_save_dir: 'models/'
  multi_gpu: false
device: cuda
