name: isles24
fold: 0
modalities: ['CBF_min_0_max_70', 'TMAX_min_4_max_30']
train_batch_size: ${environment.dataset.train_batch_size}
test_batch_size: ${environment.dataset.test_batch_size}
num_workers: ${environment.dataset.num_workers}
use_caching: false
use_shared_cache: true
train_prefetch_factor: 2
test_prefetch_factor: 2
