id: isles26
name: isles26
fold: 1
partitioning: split
subsets:
  train:
    split_in: [train]
  val_fast:
    split_in: [val_fast]
  val_rest:
    split_in: [val_rest]
  val_full:
    split_in: [val_fast, val_rest]
active_subsets:
  train: train
  val: val_fast
  sample: val_fast
label_spec:
  background: 0
  foreground: 1

preprocessing_configs:
  common:
    orientation:
      enabled: true
      axcodes: RAS
    spacing:
      enabled: false
      pixdim: [1.0, 1.0, 1.0]
      interpolation:
        image: bilinear
        label: nearest

  roi:
    volume_3d:
      - ${model.image_size}
      - ${model.image_size}
      - ${model.image_size}
    slice_2d:
      - ${model.image_size}
      - ${model.image_size}

  online_slices_3d_to_2d:
    slice_axis: 2
    slice_order: sequential

  random_patches_3d:
    patches_per_volume:
      train: 1
    rand_crop_by_pos_neg_label:
      pos: 1
      neg: 1
      image_threshold: 0.0
      allow_smaller: true
    pad_to_divisible: true

  full_volumes_3d:
    pad_to_divisible: false
