name: isles24
dir: '/mnt/c/Users/minanessiem/Development/isles24_combined'
json_list: '/mnt/c/Users/minanessiem/Development/isles24_combined/isles24_multimodal_5fold_NIHSSstratified.json'
fold: 0
modalities: ['CBF_min_0_max_70', 'TMAX_min_4_max_30']
train_batch_size: 1
test_batch_size: 1
num_workers: 12  # Suggested for ISLES24; adjust based on CPU cores