name: isles24
dir: '/mnt/datasets/isles24_combined'
json_list: '/mnt/datasets/isles24_combined/isles24_multimodal_5fold_NIHSSstratified.json'
fold: 0
modalities: ['CBF_min_0_max_70', 'TMAX_min_4_max_30']
train_batch_size: 16
test_batch_size: 4
num_workers: 48
