name: isles24
dir: '/mnt/datasets/isles24_combined'
json_list: '/mnt/datasets/isles24_combined/isles24_multimodal_5fold_NIHSSstratified.json'
fold: 0
modalities: ['CBF_min_0_max_70', 'TMAX_min_4_max_30']
train_batch_size: 16
test_batch_size: 4
num_train_workers: 64
num_valid_workers: 64
num_test_workers: 8

# Enable caching (shared or per-dataset) - set to false for low memory, slow loading (matches code default)
use_caching: false

# Whether to use a shared cache across train/val/sample (only if use_caching=true)
use_shared_cache: true  # Or false to disable sharing

# Number of batches to prefetch per worker in train DataLoader (higher = faster but more mem; e.g., 2-8)
train_prefetch_factor: 2

# Same for val/sample DataLoaders
test_prefetch_factor: 2
