# Training-specific parameters (split from default.yaml)
# num_epochs: 50  # Deprecated: Use max_steps for step-based training instead

max_steps: 100000  # Maximum training steps
checkpoint_save_interval: 500
main_checkpoint_template: 'models/diffusion_chkpt_step_{:06d}.pth'
ema_checkpoint_template: 'models/ema_chkpt_step_{:06d}_ema_{rate}.pth'
opt_checkpoint_template: 'models/opt_chkpt_step_{:06d}.pth'
ema_rate_precision: 4  # Decimal places for EMA rate in filename
ema_rate: "0.9999"  # Comma-separated for multiple, e.g. "0.999,0.9999"
