# Cluster baseline using precomputed nnUNet 2D slices as training input.
defaults:
  - cluster
  - override /environment: isles24_nnunet2d_cluster
  - override /data_runtime: ddp_cluster
  - override /distribution: ddp
  - override /optimizer: adamw_75e5lr_wd00
  - override /data_profile: isles24_2d_nnunet_baseline
  - override /loss: multitask_equal
  - override /augmentation: aggressive_2d
  - override /training: train_1Mms_ampbfloat16
  - override /scheduler: warmup_cosine_20Ksteps


environment:
  training:
    output_root: '/mnt/outputs/medsegdiff_nnunet2d_precomputed_140326/'
