defaults:
  - model: unet
  - dataset: isles24
  - training: train
  # To include eval params: hydra run +training=eval or compose in config
  - logging: default

random_seed: 42
device: cuda  # Or cpu; auto-detect in main.py if possible
mode: train  # Or evaluate

training:
  multi_gpu: false  # false -> single GPU; or comma-separated string of GPU ids like "0,1"

dataset:
  num_workers: 0  # Number of subprocesses for data loading (0 = single-process; set to 4-8 for multi-core speedup)
